name: bulssuk
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0


dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^8.0.0
  http: ^1.2.2
  table_calendar: ^3.0.6
  intl: ^0.18.0
  url_launcher: ^6.1.10
  shared_preferences: ^2.0.15
  jwt_decoder: ^2.0.1
  image_picker: ^0.8.7+4
  sqflite: ^2.0.0+4
  path: ^1.8.3
  cupertino_icons: ^1.0.8
  flutter_dotenv: ^5.2.1
  timezone: ^0.9.0
  permission_handler: ^10.2.0
  flutter_local_notifications: ^15.0.0
  ftpconnect: ^2.0.5
  web_socket_channel: ^2.2.0
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/
    - .env


