name: bulssuk
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0


dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^8.0.0
  http: ^1.2.2
  table_calendar: ^3.0.6
  intl: ^0.18.0
  url_launcher: ^6.1.10
  shared_preferences: ^2.0.15
  jwt_decoder: ^2.0.1

  cupertino_icons: ^1.0.8
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/
    - .env


